export { Doubt } from './doubt'
export { FarMeBox } from './farme_box'
export { KnowMe } from './know_me'
export { Numbers } from './numbers'
export { Targets } from './targets'
export { Testimonies } from './testimonies'
export { Main } from './initial'
