export { Summary } from './summary'
export { Values } from './values'
export { Declaration } from './declaration'
export { Testimonies } from './testimonies'
export { Main } from './initial'
export { Banner } from './banner'
export { Reasons } from './reasons'
