export default {
  ImageBoxWhoWeAre: require('./images/home-image.png'),
  ImageBoxPointingLeft: require('./images/box-direction-left.png'),
  ImageBoxPointingCenter: require('./images/box-direction-center.png'),
  ImageBoxPointingRight: require('./images/box-direction-right.png'),
  ImageHandWithDrugs: require('./images/hand-with-drugs.png'),
  ImagePersonReceivedBox: require('./images/person-received-box.png'),
  ImageBill: require('./images/bill.png'),
  ImagePerson: require('./images/person_2.png'),
  ImageBanner: require('./images/banner.png'),
  ImageBannerOlderWoman: require('./images/banner2.png'),
  IllustrationCalendar: require('./images/illustration_calendar.svg'),
  IllustrationCare: require('./images/illustration_care.svg'),
  IllustrationMedical: require('./images/illustration_medical.svg'),
}
