export default {
  ImageBoxWhoWeAre: require('./images/home-image.png'),
  ImageCoverFameBox: require('./images/imagem-cover-farmebox.png'),
  ImageBoxPointingLeft: require('./images/box-direction-left.png'),
  ImageBoxPointingCenter: require('./images/box-direction-center.png'),
  ImageBoxPointingRight: require('./images/box-direction-right.png'),
  ImageHandWithDrugs: require('./images/hand-with-drugs.png'),
  ImagePersonReceivedBox: require('./images/person-received-box.png'),
  ImageBill: require('./images/bill.png'),
  ImagePerson: require('./images/person_2.png'),
  ImagePeopleInStore: require('./images/people-in-store.png'),
  ImagePeopleInLab: require('./images/person-in-lab.png'),
  ImageBoxReceived: require('./images/box-received.png'),
  ImageOldManPhone: require('./images/old-man-phone.png'),
  ImageOldWomanInComputer: require('./images/old-woman-in-computer.png'),
  ImageDoctorWihPhone: require('./images/doctor-with-phone.png'),
  ImageDoctorLooking: require('./images/doctor-looking.png'),
  ImageBanner: require('./images/banner.png'),
  ImageBannerOlderWoman: require('./images/banner2.png'),
  ImageMedicalCare: require('./images/medical-care.png'),
  ImageOldWomanSited: require('./images/old-woman-sited.png'),
  ImageWomanWithTablet: require('./images/woman-with-tablet.png'),
  ImageAsianOldWoman: require('./images/asian-old-woman.png'),
}
